# config.py
import numpy as np

# 1. Cấu hình Mạng (Network Configuration)
NUM_APS = 6
NUM_STAS_PER_AP = 10          # default K, sẽ bị override bởi run_experiments.py
BANDWIDTH = 20e6
FREQ_C = 5.0
P_MAX = 0.1
AREA_SIZE = 100.0

# 2. Cấu hình Kênh truyền (Channel & Propagation)
L_W = 7.0
D_BP = 10.0
SHADOW_STD = 4.0
NOISE_POWER_DBM = -100
NOISE_POWER = 10 ** (NOISE_POWER_DBM / 10) * 1e-3
TX_POWER_LEVELS = [0.01, 0.02, 0.05, 0.1]
AP_CIRCUIT_POWER_W = 0.05

# AP_LOAD_PROFILE được set động theo K trong run_experiments.py
# Default: K=10 cho tất cả AP
AP_LOAD_PROFILE = [NUM_STAS_PER_AP] * NUM_APS
AP_STA_RADIUS_MAX = [18, 24, 30, 36, 28, 34]
AP_SHADOW_BIAS_DB = [-2.0, -1.0, 0.5, 2.0, 3.5, 5.0]

# 3. Cấu hình AI
CCA_THRESHOLDS = [-82, -78, -74, -70, -66, -62, -58]
DEFAULT_CCA = -70
OBS_SIZE = 7
HYBRID_ACTION_SIZE = len(CCA_THRESHOLDS)
FULL_AI_ACTION_SIZE = len(CCA_THRESHOLDS) * len(TX_POWER_LEVELS)

# Reproducibility
GLOBAL_SEED = 2026

# Công suất
MAX_TX_POWER_DBM = 20
MAX_TX_POWER_W = 10 ** (MAX_TX_POWER_DBM / 10) * 1e-3
TOTAL_POWER_BUDGET_W = NUM_APS * 0.03
USE_WATER_FILLING_BASELINE = False

# Topology & Mobility
FIXED_TRAIN_SCENARIO = True
TRAIN_SCENARIO_SEED = 2026
TRAIN_MOBILITY_ENABLED = True

# Evaluation
EVAL_MODE = "fixed"

# Reward weights
REWARD_TOTAL_THROUGHPUT_REF_MBPS = 500.0
LOCAL_THROUGHPUT_REF_MBPS = 80.0
REWARD_GLOBAL_WEIGHT = 0.50
REWARD_LOCAL_WEIGHT = 0.10
REWARD_FAIRNESS_WEIGHT = 0.40
REWARD_ACTIVE_AP_WEIGHT = 0.0

# RL Hyperparameters
LEARNING_RATE = 1e-4
LR_DECAY_STEP = 300
LR_DECAY_GAMMA = 0.5
GAMMA = 0.95
BATCH_SIZE = 256
IB_BETA = 0.001
TARGET_UPDATE_TAU = 0.005
REPLAY_BUFFER_CAPACITY = 100000

EPSILON_START = 1.0
EPSILON_MIN = 0.02
EPSILON_DECAY_HYBRID  = 0.9895
EPSILON_DECAY_FULL_AI = 0.9930
EPSILON_DECAY = EPSILON_DECAY_FULL_AI

LATENT_SIZE_HYBRID  = 16
LATENT_SIZE_FULL_AI = 24

TRAIN_EPISODES = 700
TRAIN_STEPS_PER_EPISODE = 100
EVAL_INTERVAL = 25
EVAL_EPISODES = 30
PLOT_SMOOTHING_WINDOW = 25
PLOT_SKIP_INITIAL_EPISODES = 0

# 3 seeds để cân bằng giữa độ tin cậy thống kê và thời gian train
FINAL_SEEDS = [0, 1, 2]

assert len(AP_LOAD_PROFILE) == NUM_APS
assert len(AP_STA_RADIUS_MAX) == NUM_APS
assert len(AP_SHADOW_BIAS_DB) == NUM_APS
